public enum  QueueStatus {
    AST_DEVICE_UNKNOWN,
    AST_DEVICE_NOT_INUSE,
    AST_DEVICE_INUSE,
    AST_DEVICE_BUSY,
    AST_DEVICE_INVALID,
    AST_DEVICE_UNAVAILABLE,
    AST_DEVICE_RINGING,
    AST_DEVICE_RINGINUSE,
    AST_DEVICE_ONHOLD
}